#!/usr/bin/env python3
"""Generate 02_collection_and_cleaning.ipynb as valid JSON."""

import json

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# Notebook 2: Thu Thập & Làm Sạch Dữ Liệu (Data Collection & Cleaning)\n",
                "\n",
                "**Chuyên đề 4: Phân Tích Thị Trường Việc Làm & Gợi Ý Ứng Viên**\n",
                "**Môn:** Lập trình cho Khoa học Dữ liệu\n",
                "**Buổi:** 5 — Thu thập & Làm sạch dữ liệu\n",
                "**Ngày:** 2025-07-20\n",
                "\n",
                "---\n",
                "\n",
                "## Mục tiêu\n",
                "1. **Thu thập dữ liệu** từ ít nhất 2 trang tuyển dụng Việt Nam (itviec, vietnamworks, topdev, careerbuilder)\n",
                "2. **Lưu dữ liệu thô** (raw) vào `data/raw/` theo chuẩn CSV/JSON\n",
                "3. **Chuẩn hóa lương** (SalaryParser) — xử lý 10+ format thực tế Việt Nam\n",
                "4. **Chuẩn hóa kỹ năng** (SkillNormalizer) — synonym map 35+ entry, ≥20 skill canonical\n",
                "5. **Chuẩn hóa kinh nghiệm** (ExperienceNormalizer) — parse years, bin entry/junior/mid/senior/lead\n",
                "6. **Khử trùng lặp** (Deduplicator) — exact + fuzzy (title 80%, desc 70%)\n",
                "7. **Xử lý missing & type error** — swap min/max, fill/flag missing\n",
                "8. **Hợp nhất dữ liệu** — merge jobs + skills + companies thành 1 DataFrame denormalized\n",
                "9. **Verify requirements**: ≥1000 rows, ≥12 columns, ≥3 cities\n",
                "\n",
                "> ⚠️ **Lưu ý**: Nếu các trang web block crawler, dùng `generate_fallback_data()` để tạo dữ liệu mẫu realistic. Rõ ràng ghi log đây là fallback data."
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Section 1: Thu thập dữ liệu (Data Collection)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Setup path & imports\n",
                "import sys\n",
                "sys.path.append('..')\n",
                "\n",
                "import pandas as pd\n",
                "import numpy as np\n",
                "import logging\n",
                "import warnings\n",
                "warnings.filterwarnings('ignore')\n",
                "\n",
                "# Setup logging\n",
                "logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')\n",
                "\n",
                "# Import collector, data_manager, salary_parser, domain classes\n",
                "from src.data import collector\n",
                "from src.data.data_manager import JobDataManager\n",
                "from src.data.salary_parser import SalaryParser, parse_salary\n",
                "from src.domain import JobPosting, Skill, Company\n",
                "\n",
                "print(\"✅ Imports successful\")\n",
                "print(f\"Pandas: {pd.__version__}\")\n",
                "print(f\"NumPy: {np.__version__}\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Test scrapers: ITViec (primary)\n",
                "print(\"=== Testing ITViec scraper ===\")\n",
                "try:\n",
                "    itviec_jobs = collector.scrape_itviec(keyword=\"python\", max_pages=1)\n",
                "    print(f\"✅ ITViec: {len(itviec_jobs)} jobs scraped\")\n",
                "    if itviec_jobs:\n",
                "        print(f\"   Sample: {itviec_jobs[0]['job_title']} at {itviec_jobs[0]['company_name']}\")\n",
                "except Exception as e:\n",
                "    print(f\"⚠️ ITViec blocked/error: {e}\")\n",
                "    itviec_jobs = []\n",
                "\n",
                "# Test VietnamWorks\n",
                "print(\"\\n=== Testing VietnamWorks scraper ===\")\n",
                "try:\n",
                "    vw_jobs = collector.scrape_vietnamworks(keyword=\"it\", max_pages=1)\n",
                "    print(f\"✅ VietnamWorks: {len(vw_jobs)} jobs scraped\")\n",
                "    if vw_jobs:\n",
                "        print(f\"   Sample: {vw_jobs[0]['job_title']} at {vw_jobs[0]['company_name']}\")\n",
                "except Exception as e:\n",
                "    print(f\"⚠️ VietnamWorks blocked/error: {e}\")\n",
                "    vw_jobs = []\n",
                "\n",
                "# Test TopDev\n",
                "print(\"\\n=== Testing TopDev scraper ===\")\n",
                "try:\n",
                "    topdev_jobs = collector.scrape_topdev(keyword=\"python\", max_pages=1)\n",
                "    print(f\"✅ TopDev: {len(topdev_jobs)} jobs scraped\")\n",
                "    if topdev_jobs:\n",
                "        print(f\"   Sample: {topdev_jobs[0]['job_title']} at {topdev_jobs[0]['company_name']}\")\n",
                "except Exception as e:\n",
                "    print(f\"⚠️ TopDev blocked/error: {e}\")\n",
                "    topdev_jobs = []\n",
                "\n",
                "# Test CareerBuilder\n",
                "print(\"\\n=== Testing CareerBuilder scraper ===\")\n",
                "try:\n",
                "    cb_jobs = collector.scrape_careerbuilder(keyword=\"lap trinh\", max_pages=1)\n",
                "    print(f\"✅ CareerBuilder: {len(cb_jobs)} jobs scraped\")\n",
                "    if cb_jobs:\n",
                "        print(f\"   Sample: {cb_jobs[0]['job_title']} at {cb_jobs[0]['company_name']}\")\n",
                "except Exception as e:\n",
                "    print(f\"⚠️ CareerBuilder blocked/error: {e}\")\n",
                "    cb_jobs = []\n",
                "\n",
                "# Summary\n",
                "all_real_jobs = itviec_jobs + vw_jobs + topdev_jobs + cb_jobs\n",
                "print(f\"\\n📊 Total real jobs scraped: {len(all_real_jobs)}\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# If all sites blocked or insufficient, use fallback data\n",
                "MIN_JOBS_REQUIRED = 1500\n",
                "\n",
                "if len(all_real_jobs) < MIN_JOBS_REQUIRED:\n",
                "    print(f\"\\n⚠️ Only {len(all_real_jobs)} real jobs (< {MIN_JOBS_REQUIRED}), generating fallback data...\")\n",
                "    fallback = collector.generate_fallback_data(n_jobs=MIN_JOBS_REQUIRED - len(all_real_jobs))\n",
                "    print(f\"✅ Generated {len(fallback['jobs'])} fallback jobs\")\n",
                "    print(f\"✅ Generated {len(fallback['skills'])} fallback skills\")\n",
                "    print(f\"✅ Generated {len(fallback['companies'])} fallback companies\")\n",
                "    \n",
                "    # Combine real + fallback\n",
                "    all_jobs = all_real_jobs + fallback[\"jobs\"]\n",
                "    all_skills = []\n",
                "    for job in all_real_jobs:\n",
                "        for skill in job.get(\"skills_raw\", []):\n",
                "            all_skills.append({\n",
                "                \"job_id\": job[\"job_id\"],\n",
                "                \"skill_name\": skill,\n",
                "                \"original_name\": skill,\n",
                "                \"skill_group\": \"Other\",\n",
                "                \"required_level\": \"Not specified\",\n",
                "            })\n",
                "    all_skills.extend(fallback[\"skills\"])\n",
                "    \n",
                "    # Build companies from real jobs\n",
                "    company_map = {}\n",
                "    import hashlib\n",
                "    for job in all_real_jobs:\n",
                "        cid = f\"comp_{hashlib.md5(job['company_name'].encode()).hexdigest()[:8]}\"\n",
                "        if cid not in company_map:\n",
                "            company_map[cid] = {\n",
                "                \"company_id\": cid,\n",
                "                \"company_name\": job[\"company_name\"],\n",
                "                \"company_size\": \"Unknown\",\n",
                "                \"industry\": \"Information Technology\",\n",
                "                \"city\": job[\"city\"],\n",
                "                \"source_site\": job[\"source_site\"],\n",
                "            }\n",
                "    all_companies = list(company_map.values()) + fallback[\"companies\"]\n",
                "    \n",
                "    is_fallback = True\n",
                "else:\n",
                "    print(f\"\\n✅ Sufficient real jobs: {len(all_real_jobs)} >= {MIN_JOBS_REQUIRED}\")\n",
                "    all_jobs = all_real_jobs\n",
                "    # Build skills & companies from real jobs\n",
                "    all_skills = []\n",
                "    for job in all_real_jobs:\n",
                "        for skill in job.get(\"skills_raw\", []):\n",
                "            all_skills.append({\n",
                "                \"job_id\": job[\"job_id\"],\n",
                "                \"skill_name\": skill,\n",
                "                \"original_name\": skill,\n",
                "                \"skill_group\": \"Other\",\n",
                "                \"required_level\": \"Not specified\",\n",
                "            })\n",
                "    \n",
                "    company_map = {}\n",
                "    import hashlib\n",
                "    for job in all_real_jobs:\n",
                "        cid = f\"comp_{hashlib.md5(job['company_name'].encode()).hexdigest()[:8]}\"\n",
                "        if cid not in company_map:\n",
                "            company_map[cid] = {\n",
                "                \"company_id\": cid,\n",
                "                \"company_name\": job[\"company_name\"],\n",
                "                \"company_size\": \"Unknown\",\n",
                "                \"industry\": \"Information Technology\",\n",
                "                \"city\": job[\"city\"],\n",
                "                \"source_site\": job[\"source_site\"],\n",
                "            }\n",
                "    all_companies = list(company_map.values())\n",
                "    is_fallback = False\n",
                "\n",
                "print(f\"\\n📊 Final totals: {len(all_jobs)} jobs, {len(all_skills)} skills, {len(all_companies)} companies\")\n",
                "print(f\"   Fallback used: {is_fallback}\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Save raw data using JobDataManager\n",
                "dm = JobDataManager()\n",
                "\n",
                "# Convert dicts to domain objects\n",
                "from src.domain import JobPosting, Skill, Company\n",
                "from datetime import datetime\n",
                "import hashlib\n",
                "\n",
                "job_objects = []\n",
                "for job in all_jobs:\n",
                "    posted_at = None\n",
                "    if job.get(\"posted_date_raw\"):\n",
                "        try:\n",
                "            posted_at = datetime.fromisoformat(job[\"posted_date_raw\"])\n",
                "        except:\n",
                "            pass\n",
                "    \n",
                "    # Parse salary raw if available\n",
                "    salary_min = job.get(\"salary_min\")\n",
                "    salary_max = job.get(\"salary_max\")\n",
                "    salary_hidden = job.get(\"salary_hidden\", False)\n",
                "    \n",
                "    job_obj = JobPosting(\n",
                "        job_id=job[\"job_id\"],\n",
                "        job_title=job[\"job_title\"],\n",
                "        company_id=f\"comp_{hashlib.md5(job['company_name'].encode()).hexdigest()[:8]}\",\n",
                "        industry=\"Information Technology\",\n",
                "        city=job[\"city\"],\n",
                "        experience_years=job.get(\"experience_years\"),\n",
                "        education_level=job.get(\"education_level\", \"Not Required\"),\n",
                "        job_type=job.get(\"job_type\", \"Full-time\"),\n",
                "        remote_option=job.get(\"remote_option\", \"On-site\"),\n",
                "        salary_min=salary_min,\n",
                "        salary_max=salary_max,\n",
                "        salary_hidden=salary_hidden,\n",
                "        posted_at=posted_at,\n",
                "        description=job.get(\"description_raw\", \"\"),\n",
                "        source_url=job[\"source_url\"],\n",
                "        source_site=job[\"source_site\"],\n",
                "    )\n",
                "    job_objects.append(job_obj)\n",
                "\n",
                "skill_objects = [\n",
                "    Skill(\n",
                "        skill_name=s[\"skill_name\"],\n",
                "        original_name=s[\"original_name\"],\n",
                "        skill_group=s[\"skill_group\"],\n",
                "        required_level=s[\"required_level\"],\n",
                "        job_id=s[\"job_id\"],\n",
                "    )\n",
                "    for s in all_skills\n",
                "]\n",
                "\n",
                "company_objects = [\n",
                "    Company(\n",
                "        company_id=c[\"company_id\"],\n",
                "        company_name=c[\"company_name\"],\n",
                "        company_size=c[\"company_size\"],\n",
                "        industry=c[\"industry\"],\n",
                "        city=c[\"city\"],\n",
                "        source_site=c[\"source_site\"],\n",
                "    )\n",
                "    for c in all_companies\n",
                "]\n",
                "\n",
                "# Save raw data\n",
                "print(\"Saving raw data...\")\n",
                "jobs_path = dm.save_raw_jobs(job_objects, source_site=\"combined\")\n",
                "skills_path = dm.save_raw_skills(skill_objects, source_site=\"combined\")\n",
                "companies_path = dm.save_raw_companies(companies_path=dm.save_raw_companies(companies=company_objects, source_site=\"combined\"))\n",
                "\n",
                "print(f\"✅ Jobs saved to: {jobs_path}\")\n",
                "print(f\"✅ Skills saved to: {skills_path}\")\n",
                "print(f\"✅ Companies saved to: {companies_path}\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Load raw data back and show first 5 rows, shape, source distribution\n",
                "jobs_df = dm.load_raw_jobs()\n",
                "skills_df = dm.load_raw_skills()\n",
                "companies_df = dm.load_raw_companies()\n",
                "\n",
                "print(\"=== JOBS (first 5 rows) ===\")\n",
                "print(jobs_df.head())\n",
                "print(f\"\\nShape: {jobs_df.shape}\")\n",
                "print(f\"\\nSource distribution:\")\n",
                "print(jobs_df['source_site'].value_counts())\n",
                "print(f\"\\nCities:\")\n",
                "print(jobs_df['city'].value_counts())\n",
                "print(f\"\\nColumns: {list(jobs_df.columns)}\")\n",
                "\n",
                "print(\"\\n=== SKILLS (first 5 rows) ===\")\n",
                "print(skills_df.head())\n",
                "print(f\"\\nShape: {skills_df.shape}\")\n",
                "\n",
                "print(\"\\n=== COMPANIES (first 5 rows) ===\")\n",
                "print(companies_df.head())\n",
                "print(f\"\\nShape: {companies_df.shape}\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Section 2: Kiểm tra dữ liệu gốc (Raw Data Inspection)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Load raw data\n",
                "jobs_df = dm.load_raw_jobs()\n",
                "skills_df = dm.load_raw_skills()\n",
                "companies_df = dm.load_raw_companies()\n",
                "\n",
                "print(\"=== JOBS INFO ===\")\n",
                "jobs_df.info()\n",
                "\n",
                "print(\"\\n=== SKILLS INFO ===\")\n",
                "skills_df.info()\n",
                "\n",
                "print(\"\\n=== COMPANIES INFO ===\")\n",
                "companies_df.info()"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Missing values statistics\n",
                "print(\"=== MISSING VALUES (jobs) ===\")\n",
                "missing_jobs = jobs_df.isnull().sum()\n",
                "missing_pct = (missing_jobs / len(jobs_df) * 100).round(2)\n",
                "missing_df = pd.DataFrame({'missing_count': missing_jobs, 'missing_pct': missing_pct})\n",
                "print(missing_df[missing_df['missing_count'] > 0])\n",
                "\n",
                "print(\"\\n=== MISSING VALUES (skills) ===\")\n",
                "missing_skills = skills_df.isnull().sum()\n",
                "missing_pct_s = (missing_skills / len(skills_df) * 100).round(2)\n",
                "missing_df_s = pd.DataFrame({'missing_count': missing_skills, 'missing_pct': missing_pct_s})\n",
                "print(missing_df_s[missing_df_s['missing_count'] > 0])\n",
                "\n",
                "print(\"\\n=== MISSING VALUES (companies) ===\")\n",
                "missing_comp = companies_df.isnull().sum()\n",
                "missing_pct_c = (missing_comp / len(companies_df) * 100).round(2)\n",
                "missing_df_c = pd.DataFrame({'missing_count': missing_comp, 'missing_pct': missing_pct_c})\n",
                "print(missing_df_c[missing_df_c['missing_count'] > 0])"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# NumPy stats for salary and experience\n",
                "print(\"=== SALARY & EXPERIENCE STATS (NumPy) ===\")\n",
                "\n",
                "for col in ['salary_min', 'salary_max', 'experience_years']:\n",
                "    if col in jobs_df.columns:\n",
                "        vals = jobs_df[col].dropna()\n",
                "        if len(vals) > 0:\n",
                "            print(f\"\\n{col}:\")\n",
                "            print(f\"  Count: {len(vals)}\")\n",
                "            print(f\"  Mean: {np.mean(vals):.2f}\")\n",
                "            print(f\"  Median: {np.median(vals):.2f}\")\n",
                "            print(f\"  Std: {np.std(vals):.2f}\")\n",
                "            print(f\"  Min: {np.min(vals):.2f}\")\n",
                "            print(f\"  Max: {np.max(vals):.2f}\")\n",
                "            print(f\"  25%: {np.percentile(vals, 25):.2f}\")\n",
                "            print(f\"  75%: {np.percentile(vals, 75):.2f}\")\n",
                "        else:\n",
                "            print(f\"\\n{col}: No valid values\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Count unique jobs, companies, skills\n",
                "print(\"=== UNIQUE COUNTS ===\")\n",
                "print(f\"Unique jobs: {jobs_df['job_id'].nunique()}\")\n",
                "print(f\"Unique companies: {companies_df['company_id'].nunique() if 'company_id' in companies_df.columns else companies_df['company_name'].nunique()}\")\n",
                "print(f\"Unique skills: {skills_df['skill_name'].nunique() if 'skill_name' in skills_df.columns else 0}\")\n",
                "print(f\"Unique cities: {jobs_df['city'].nunique()}\")\n",
                "print(f\"Unique source sites: {jobs_df['source_site'].nunique()}\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Section 3: Salary Parsing"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Demo SalaryParser with examples\n",
                "parser = SalaryParser()\n",
                "\n",
                "test_cases = [\n",
                "    \"10-15 triệu\",\n",
                "    \"10 – 15 triệu\",\n",
                "    \"10-15tr\",\n",
                "    \"tới 20 triệu\",\n",
                "    \"đến 20 triệu\",\n",
                "    \"từ 15 triệu\",\n",
                "    \"80-120 triệu/năm\",\n",
                "    \"1200-1800 USD\",\n",
                "    \"$1500-2000\",\n",
                "    \"cạnh tranh\",\n",
                "    \"thỏa thuận\",\n",
                "    \"negotiable\",\n",
                "    \"15 triệu\",\n",
                "    \"20M\",\n",
                "    \"1000-2000 USD/tháng\",\n",
                "    \"tối đa 30 triệu\",\n",
                "    \"min 10 triệu\",\n",
                "    \"5000-8000 USD\",\n",
                "]\n",
                "\n",
                "print(\"=== SALARY PARSER DEMO ===\")\n",
                "for tc in test_cases:\n",
                "    result = parser.parse(tc)\n",
                "    print(f\"'{tc}' -> min={result.salary_min}, max={result.salary_max}, mid={result.salary_mid}, hidden={result.is_hidden}, type={result.salary_type.value}, conf={result.confidence}\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Apply to job postings column\n",
                "jobs_df = dm.load_raw_jobs()\n",
                "\n",
                "# Parse salary from raw column (salary_raw or salary_min/max if already split)\n",
                "if 'salary_raw' in jobs_df.columns:\n",
                "    jobs_df = parser.parse_column(jobs_df, 'salary_raw')\n",
                "else:\n",
                "    # Already has salary_min/max, just parse for hidden detection\n",
                "    jobs_df = parser.parse_column(jobs_df, 'salary_min')\n",
                "\n",
                "# Show statistics\n",
                "total = len(jobs_df)\n",
                "hidden_count = jobs_df['salary_hidden'].sum() if 'salary_hidden' in jobs_df.columns else 0\n",
                "parsed_count = jobs_df['salary_min'].notna().sum() if 'salary_min' in jobs_df.columns else 0\n",
                "\n",
                "print(f\"=== SALARY PARSING STATS ===\")\n",
                "print(f\"Total jobs: {total}\")\n",
                "print(f\"Parsed (has min or max): {parsed_count}\")\n",
                "print(f\"Hidden salary rate: {hidden_count}/{total} = {hidden_count/total*100:.1f}%\")\n",
                "\n",
                "if 'salary_min' in jobs_df.columns:\n",
                "    vals = jobs_df['salary_min'].dropna()\n",
                "    if len(vals) > 0:\n",
                "        print(f\"\\nSalary min stats:\")\n",
                "        print(f\"  Mean: {vals.mean():.1f} triệu VND\")\n",
                "        print(f\"  Median: {vals.median():.1f} triệu VND\")\n",
                "        print(f\"  Std: {vals.std():.1f}\")\n",
                "\n",
                "if 'salary_max' in jobs_df.columns:\n",
                "    vals = jobs_df['salary_max'].dropna()\n",
                "    if len(vals) > 0:\n",
                "        print(f\"\\nSalary max stats:\")\n",
                "        print(f\"  Mean: {vals.mean():.1f} triệu VND\")\n",
                "        print(f\"  Median: {vals.median():.1f} triệu VND\")\n",
                "        print(f\"  Std: {vals.std():.1f}\")\n",
                "\n",
                "if 'salary_mid' in jobs_df.columns:\n",
                "    vals = jobs_df['salary_mid'].dropna()\n",
                "    if len(vals) > 0:\n",
                "        print(f\"\\nSalary mid (avg) stats:\")\n",
                "        print(f\"  Mean: {vals.mean():.1f} triệu VND\")\n",
                "        print(f\"  Median: {vals.median():.1f} triệu VND\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Section 4: Skill Normalization"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Demo SkillNormalizer\n",
                "from src.cleaning.skill_normalizer import SkillNormalizer\n",
                "\n",
                "normalizer = SkillNormalizer()\n",
                "\n",
                "test_skills = [\n",
                "    \"JavaScript\", \"JS\", \"java script\", \"ReactJS\", \"react.js\", \"vuejs\",\n",
                "    \"Python3\", \"py\", \"golang\", \"Go\", \"C++\", \"cpp\", \"nodejs\", \"node.js\",\n",
                "    \"postgresql\", \"postgres\", \"mysql\", \"mongo\", \"mongodb\",\n",
                "    \"aws\", \"amazon web services\", \"docker\", \"k8s\", \"kubernetes\",\n",
                "    \"machine learning\", \"ml\", \"deep learning\", \"tensorflow\", \"pytorch\",\n",
                "    \"English\", \"tiếng anh\", \"ielts\", \"teamwork\", \"leadership\",\n",
                "    \"UnknownSkill123\", \"RandomFrameworkXYZ\",\n",
                "]\n",
                "\n",
                "print(\"=== SKILL NORMALIZER DEMO ===\")\n",
                "for skill in test_skills:\n",
                "    result = normalizer.normalize(skill)\n",
                "    print(f\"'{skill}' -> '{result.canonical}' [{result.skill_group}] matched={result.matched} conf={result.confidence}\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Apply to skills dataframe\n",
                "skills_df = dm.load_raw_skills()\n",
                "\n",
                "if 'skill_name' in skills_df.columns:\n",
                "    skills_df = normalizer.normalize_dataframe(skills_df, col='skill_name',\n",
                "        new_canonical_col='skill_name_canonical',\n",
                "        new_group_col='skill_group',\n",
                "        new_matched_col='skill_matched',\n",
                "        log_file='logs/unmatched_skills.log')\n",
                "    \n",
                "    # Show matched/unmatched counts\n",
                "    total = len(skills_df)\n",
                "    matched = skills_df['skill_matched'].sum()\n",
                "    unmatched = total - matched\n",
                "    \n",
                "    print(f\"=== SKILL NORMALIZATION STATS ===\")\n",
                "    print(f\"Total skills: {total}\")\n",
                "    print(f\"Matched: {matched} ({matched/total*100:.1f}%)\")\n",
                "    print(f\"Unmatched: {unmatched} ({unmatched/total*100:.1f}%)\")\n",
                "\n",
                "    # Show top 20 canonical skills\n",
                "    if 'skill_name_canonical' in skills_df.columns:\n",
                "        top20 = skills_df['skill_name_canonical'].value_counts().head(20)\n",
                "        print(f\"\\n=== TOP 20 CANONICAL SKILLS ===\")\n",
                "        for skill, count in top20.items():\n",
                "            print(f\"  {skill}: {count}\")\n",
                "else:\n",
                "    print(\"No skill_name column in skills_df\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Section 5: Experience Normalization"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Demo ExperienceNormalizer\n",
                "from src.cleaning.experience_normalizer import ExperienceNormalizer\n",
                "\n",
                "exp_normalizer = ExperienceNormalizer()\n",
                "\n",
                "test_cases = [\n",
                "    \"2 năm\", \"3 năm kinh nghiệm\", \"5 năm\",\n",
                "    \"2-5 năm\", \"3 - 5 năm\", \"2–5 năm\",\n",
                "    \"từ 3 năm\", \"từ 5 năm kinh nghiệm\",\n",
                "    \"tới 5 năm\", \"đến 3 năm\", \"dưới 2 năm\",\n",
                "    \"hơn 5 năm\", \"trên 3 năm\", \"ít nhất 2 năm\",\n",
                "    \"3+ năm\", \"5+ years\",\n",
                "    \"fresher\", \"new grad\", \"mới ra trường\", \"chưa có kinh nghiệm\",\n",
                "    \"1 year\", \"2 years\", \"5 yr\",\n",
                "    \"10 năm\", \"15 năm\",\n",
                "    \"unknown\", \"không rõ\", \"\",\n",
                "]\n",
                "\n",
                "print(\"=== EXPERIENCE NORMALIZER DEMO ===\")\n",
                "for tc in test_cases:\n",
                "    result = exp_normalizer.parse_years(tc)\n",
                "    print(f\"'{tc}' -> years={result.years}, bin={result.experience_bin}, parsed={result.parsed}\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Apply to experience column\n",
                "jobs_df = dm.load_raw_jobs()\n",
                "\n",
                "# Check if experience_raw or experience_years exists\n",
                "exp_col = None\n",
                "for col in ['experience_raw', 'experience_years']:\n",
                "    if col in jobs_df.columns:\n",
                "        exp_col = col\n",
                "        break\n",
                "\n",
                "if exp_col:\n",
                "    jobs_df = exp_normalizer.parse_dataframe(jobs_df, col=exp_col,\n",
                "        years_col='experience_years',\n",
                "        bin_col='experience_bin',\n",
                "        parsed_col='experience_parsed')\n",
                "    \n",
                "    # Show distribution of experience_bin\n",
                "    if 'experience_bin' in jobs_df.columns:\n",
                "        print(f\"=== EXPERIENCE BIN DISTRIBUTION ===\")\n",
                "        print(jobs_df['experience_bin'].value_counts())\n",
                "        print(f\"\\nTotal: {len(jobs_df)}\")\n",
                "        parsed = jobs_df['experience_parsed'].sum() if 'experience_parsed' in jobs_df.columns else 0\n",
                "        print(f\"Parsed: {parsed} ({parsed/len(jobs_df)*100:.1f}%)\")\n",
                "else:\n",
                "    print(\"No experience column found in jobs_df\")\n",
                "    print(f\"Available columns: {list(jobs_df.columns)}\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Section 6: Deduplication"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Run Deduplicator\n",
                "from src.cleaning.deduplicator import Deduplicator\n",
                "\n",
                "jobs_df = dm.load_raw_jobs()\n",
                "skills_df = dm.load_raw_skills()\n",
                "\n",
                "# Ensure we have necessary columns\n",
                "print(f\"Jobs columns: {list(jobs_df.columns)}\")\n",
                "print(f\"Skills columns: {list(skills_df.columns)}\")\n",
                "\n",
                "dedup = Deduplicator(title_threshold=0.8, desc_threshold=0.7)\n",
                "groups = dedup.find_duplicates(jobs_df)\n",
                "\n",
                "# Show stats\n",
                "stats = dedup.analyze_duplicates(jobs_df, groups)\n",
                "print(f\"=== DEDUPLICATION STATS ===\")\n",
                "print(f\"Total duplicate groups: {stats['total_groups']}\")\n",
                "print(f\"Total duplicates to remove: {stats['total_duplicates']}\")\n",
                "print(f\"Exact duplicates: {stats['exact_duplicates']}\")\n",
                "print(f\"Near (fuzzy) duplicates: {stats['near_duplicates']}\")\n",
                "print(f\"Average similarity score: {stats['avg_score']:.2f}\")\n",
                "\n",
                "# Log duplicates\n",
                "dedup.log_duplicates(jobs_df, groups)\n",
                "\n",
                "# Remove duplicates\n",
                "jobs_df_dedup = dedup.remove_duplicates(jobs_df, groups)\n",
                "print(f\"\\nOriginal: {len(jobs_df)}, After dedup: {len(jobs_df_dedup)}\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Section 7: Missing & Type Error Handling"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Report missing rate per column\n",
                "jobs_df = jobs_df_dedup if 'jobs_df_dedup' in locals() else dm.load_raw_jobs()\n",
                "\n",
                "print(\"=== MISSING RATE PER COLUMN ===\")\n",
                "missing_report = jobs_df.isnull().sum() / len(jobs_df) * 100\n",
                "missing_report = missing_report[missing_report > 0].sort_values(ascending=False)\n",
                "for col, pct in missing_report.items():\n",
                "    print(f\"  {col}: {pct:.1f}%\")\n",
                "\n",
                "# Check salary_min/max swap\n",
                "if 'salary_min' in jobs_df.columns and 'salary_max' in jobs_df.columns:\n",
                "    swapped = jobs_df[(jobs_df['salary_min'] > jobs_df['salary_max']) & \n",
                "                    jobs_df['salary_min'].notna() & jobs_df['salary_max'].notna()]\n",
                "    print(f\"\\n=== SALARY MIN/MAX SWAPPED: {len(swapped)} rows ===\")\n",
                "    if len(swapped) > 0:\n",
                "        print(swapped[['job_id', 'job_title', 'salary_min', 'salary_max']].head(10))\n",
                "        \n",
                "        # Fix: swap them back\n",
                "        jobs_df.loc[swapped.index, ['salary_min', 'salary_max']] = \\\n",
                "            jobs_df.loc[swapped.index, ['salary_max', 'salary_min']].values\n",
                "        print(\"✅ Swapped salary_min/max fixed\")\n",
                "\n",
                "# Fill/flag missing values\n",
                "print(\"\\n=== MISSING HANDLING ===\")\n",
                "# For salary: already have salary_hidden flag\n",
                "# For experience: fill with median if missing\n",
                "if 'experience_years' in jobs_df.columns:\n",
                "    exp_median = jobs_df['experience_years'].median()\n",
                "    missing_exp = jobs_df['experience_years'].isna().sum()\n",
                "    if missing_exp > 0:\n",
                "        jobs_df['experience_years'] = jobs_df['experience_years'].fillna(exp_median)\n",
                "        print(f\"Filled {missing_exp} missing experience_years with median: {exp_median}\")\n",
                "\n",
                "# For city: fill with 'Unknown'\n",
                "if 'city' in jobs_df.columns:\n",
                "    missing_city = jobs_df['city'].isna().sum()\n",
                "    if missing_city > 0:\n",
                "        jobs_df['city'] = jobs_df['city'].fillna('Unknown')\n",
                "        print(f\"Filled {missing_city} missing city with 'Unknown'\")\n",
                "\n",
                "# For education_level\n",
                "if 'education_level' in jobs_df.columns:\n",
                "    missing_edu = jobs_df['education_level'].isna().sum()\n",
                "    if missing_edu > 0:\n",
                "        jobs_df['education_level'] = jobs_df['education_level'].fillna('Not Required')\n",
                "        print(f\"Filled {missing_edu} missing education_level with 'Not Required'\")\n",
                "\n",
                "# For remote_option\n",
                "if 'remote_option' in jobs_df.columns:\n",
                "    missing_remote = jobs_df['remote_option'].isna().sum()\n",
                "    if missing_remote > 0:\n",
                "        jobs_df['remote_option'] = jobs_df['remote_option'].fillna('Not specified')\n",
                "        print(f\"Filled {missing_remote} missing remote_option with 'Not specified'\")\n",
                "\n",
                "# For job_type\n",
                "if 'job_type' in jobs_df.columns:\n",
                "    missing_type = jobs_df['job_type'].isna().sum()\n",
                "    if missing_type > 0:\n",
                "        jobs_df['job_type'] = jobs_df['job_type'].fillna('Full-time')\n",
                "        print(f\"Filled {missing_type} missing job_type with 'Full-time'\")\n",
                "\n",
                "print(f\"\\nFinal shape: {jobs_df.shape}\")\n",
                "print(f\"Remaining missing:\")\n",
                "final_missing = jobs_df.isnull().sum()\n",
                "print(final_missing[final_missing > 0])"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Section 8: Hợp nhất dữ liệu (Merge)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Use JobDataManager.merge_datasets() to merge jobs + skills + companies\n",
                "jobs_df = jobs_df_dedup if 'jobs_df_dedup' in locals() else dm.load_raw_jobs()\n",
                "skills_df = dm.load_raw_skills()\n",
                "companies_df = dm.load_raw_companies()\n",
                "\n",
                "# Ensure skills has canonical names\n",
                "if 'skill_name_canonical' not in skills_df.columns:\n",
                "    skills_df = normalizer.normalize_dataframe(skills_df, col='skill_name',\n",
                "        new_canonical_col='skill_name_canonical',\n",
                "        new_group_col='skill_group',\n",
                "        new_matched_col='skill_matched')\n",
                "\n",
                "# Merge\n",
                "merged_df = dm.merge_datasets(jobs_df, skills_df, companies_df)\n",
                "\n",
                "print(f\"=== MERGED DATASET ===\")\n",
                print(f\"Shape: {merged_df.shape}\")\n",
                "print(f\"Columns ({len(merged_df.columns)}): {list(merged_df.columns)}\")\n",
                "\n",
                "# Save processed data\n",
                "processed_path = dm.save_processed(merged_df, name=\"jobs_merged\")\n",
                "print(f\"\\n✅ Processed data saved to: {processed_path}\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Show final shape and sample rows\n",
                "print(f\"=== FINAL DATASET ===\")\n",
                "print(f\"Shape: {merged_df.shape} (rows, cols)\")\n",
                "print(f\"\\nSample rows (first 5):\")\n",
                "pd.set_option('display.max_columns', None)\n",
                "pd.set_option('display.width', 200)\n",
                "pd.set_option('display.max_colwidth', 50)\n",
                "print(merged_df.head())\n",
                "\n",
                "# Verify minimum requirements\n",
                "print(f\"\\n=== REQUIREMENTS VERIFICATION ===\")\n",
                "print(f\"✅ Rows ≥ 1000: {merged_df.shape[0]} >= 1000 -> {merged_df.shape[0] >= 1000}\")\n",
                "print(f\"✅ Columns ≥ 12: {merged_df.shape[1]} >= 12 -> {merged_df.shape[1] >= 12}\")\n",
                "n_cities = merged_df['city'].nunique() if 'city' in merged_df.columns else 0\n",
                "print(f\"✅ Cities ≥ 3: {n_cities} >= 3 -> {n_cities >= 3}\")\n",
                "print(f\"   Cities: {merged_df['city'].unique() if 'city' in merged_df.columns else 'N/A'}\")\n",
                "\n",
                "# Additional stats\n",
                "print(f\"\\n=== ADDITIONAL STATS ===\")\n",
                "print(f\"Unique companies: {merged_df['company_id'].nunique() if 'company_id' in merged_df.columns else 'N/A'}\")\n",
                "print(f\"Unique job titles: {merged_df['job_title'].nunique() if 'job_title' in merged_df.columns else 'N/A'}\")\n",
                "if 'salary_mid' in merged_df.columns:\n",
                "    salary_vals = merged_df['salary_mid'].dropna()\n",
                "    if len(salary_vals) > 0:\n",
                "        print(f\"Jobs with salary: {len(salary_vals)} ({len(salary_vals)/len(merged_df)*100:.1f}%)\")\n",
                "        print(f\"Avg salary: {salary_vals.mean():.1f} triệu VND\")\n",
                "if 'skills' in merged_df.columns:\n",
                "    jobs_with_skills = merged_df['skills'].apply(lambda x: len(x) if isinstance(x, list) else 0).sum()\n",
                "    print(f\"Total skill entries: {jobs_with_skills}\")"
            ]
        }
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "codemirror_mode": {
                "name": "ipython",
                "version": 3
            },
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.10.0"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 5
}

# Write notebook
output_path = r"D:\LerningSpace\HocCaoHoc\KhoaHocDuLieu\notebooks\02_collection_and_cleaning.ipynb"
with open(output_path, 'w', encoding='utf-8') as f:
    json.dump(notebook, f, ensure_ascii=False, indent=2)

print(f"Notebook written to: {output_path}")
print("Valid JSON:", True)